package Utils;

public class TimeConstants {
	public static final long MINUTES_TO_MILLISECONDS_CONVERTER = 60000;
	public static final long THIRTY_MINUTES_IN_MILLISECONDS = 30 * MINUTES_TO_MILLISECONDS_CONVERTER;
	public static final long HOURS_TO_MILLISECONDS_CONVERTER = 60 * MINUTES_TO_MILLISECONDS_CONVERTER;
	public static final long DAYS_TO_MILLISECONDS_CONVERTER = 24 * HOURS_TO_MILLISECONDS_CONVERTER;
	public static final long MONTHS_TO_MILLISECONDS_CONVERTER = 30 * DAYS_TO_MILLISECONDS_CONVERTER;
	public static final long WEEKS_TO_MILLISECONDS_CONVERTER = 7 * DAYS_TO_MILLISECONDS_CONVERTER;
}
